// Ironsworn / Starforged oracle engine.
//
// Oracle data (the ~40–260 tables per game) is generated by tools/build-oracles.mjs
// from Datasworn (CC BY 4.0, Shawn Tomkin) and lazy-loaded the way the deck art
// is. This module is the stateless engine over that data: roll a table, resolve
// the Datasworn "roll again" links, and clean the display text. It holds no
// state and no DOM — the app owns which dataset is loaded and how results show.
//
// A dataset is { id, title, authors, license, url, tree, tables } where `tree`
// is the browse structure (collections -> tables/groups) and `tables` maps a
// table id to { name, sides, rows:[{ a, b, t, r? }] }. A row's optional `r` is
// a list of links { o: targetId|null, n: rolls, auto: 0|1, dup? }.
import { randInt } from './system-dice.js';

// Datasworn embeds cross-references as markdown-style [label](id:…) / [label](type:id)
// links. For a plain reading we keep the label and drop the target, and strip
// the __bold__ emphasis Datasworn uses for the lead phrase of a row.
export function oracleText(text) {
  return String(text || '')
    .replace(/\[([^\]]+)\]\((?:id|move|oracle_rollable|asset|move_category):[^)]*\)/gi, '$1')
    .replace(/\{\{[^}]*\}\}/g, '')     // unresolved template tokens, if any
    .replace(/__([^_]+)__/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
}

function findRow(table, roll) {
  for (const row of table.rows) if (roll >= row.a && roll <= row.b) return row;
  return table.rows[table.rows.length - 1] || null;   // clamp to the last row
}

// Roll one table by id. Returns a result node:
//   { id, name, sides, roll, text, links:[…], suggested:[{ id, name, n }] }
// `links` are auto-resolved sub-rolls (nested result nodes); `suggested` are the
// optional follow-ups Datasworn marks auto:false, surfaced but not rolled.
export function rollOracle(dataset, id, rng = randInt, _depth = 0) {
  const table = dataset.tables[id];
  if (!table) throw new Error(`Unknown oracle table: ${id}`);
  const roll = rng(table.sides);
  const row = findRow(table, roll);
  const result = { id, name: table.name, sides: table.sides, roll, text: oracleText(row && row.t), links: [], suggested: [] };
  if (!row || !row.r) return result;

  for (const link of row.r) {
    const targetId = link.o || id;                      // null re-rolls this table
    const target = dataset.tables[targetId];
    if (link.auto && _depth < 4) {
      const rolls = resolveLink(dataset, targetId, link, rng, _depth + 1);
      result.links.push(...rolls);
    } else {
      result.suggested.push({ id: targetId, name: target ? target.name : targetId, n: link.n || 1 });
    }
  }
  return result;
}

// Resolve one auto link into n sub-results. "reroll" duplicates get one retry to
// land distinct; "make_it_worse" keeps repeats as-is (that is the point of it).
function resolveLink(dataset, id, link, rng, depth) {
  const count = link.n || 1;
  const out = [];
  const seen = new Set();
  for (let i = 0; i < count; i++) {
    let node = rollOracle(dataset, id, rng, depth);
    if (link.dup !== 'make_it_worse') {
      for (let retry = 0; retry < 3 && seen.has(node.roll); retry++) node = rollOracle(dataset, id, rng, depth);
    }
    seen.add(node.roll);
    out.push(node);
  }
  return out;
}

// Flatten a result node to a single reading line, e.g. for history/tooltips:
//   "Landscape Feature: Bay  +  A settlement by the water"
export function oracleReading(node) {
  const parts = [node.text];
  for (const child of node.links) parts.push(oracleReading(child));
  return parts.filter(Boolean).join(' + ');
}

// Walk the browse tree to a flat list of { id, name, path } for search/listing.
export function oracleTableList(dataset) {
  const out = [];
  const visit = (nodes, path) => {
    for (const node of nodes) {
      const here = [...path, node.name];
      for (const id of node.tables || []) {
        const t = dataset.tables[id];
        if (t) out.push({ id, name: t.name, path: here });
      }
      if (node.groups) visit(node.groups, here);
    }
  };
  visit(dataset.tree, []);
  return out;
}

// A stable, typeable handle for each table, so a table can be rolled from the
// notation field (oracle:pay-the-price, oracle:likely). Slugs are the table name
// lowercased to a-z0-9 runs; a collision takes a -2, -3 suffix in tree order, so
// they are deterministic. Built once per dataset and cached off-enumeration.
export function slugifyOracle(name) {
  return String(name || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}
function oracleSlugMaps(dataset) {
  if (dataset.__slugMaps) return dataset.__slugMaps;
  const slugToId = Object.create(null), idToSlug = Object.create(null);
  for (const { id, name } of oracleTableList(dataset)) {
    const base = slugifyOracle(name) || 'table';
    let slug = base, i = 2;
    while (slugToId[slug]) slug = `${base}-${i++}`;
    slugToId[slug] = id;
    idToSlug[id] = slug;
  }
  Object.defineProperty(dataset, '__slugMaps', { value: { slugToId, idToSlug }, enumerable: false });
  return dataset.__slugMaps;
}
export function oracleSlug(dataset, id) { return oracleSlugMaps(dataset).idToSlug[id]; }

// Resolve a typed query to a table id: exact slug first, then a unique prefix
// match (so "oracle:pay" reaches "pay-the-price" when nothing else starts that
// way). Returns null when nothing matches or a prefix is ambiguous.
export function findOracleBySlug(dataset, query) {
  const maps = oracleSlugMaps(dataset);
  const q = slugifyOracle(query);
  if (!q) return null;
  if (maps.slugToId[q]) return maps.slugToId[q];
  const hits = Object.keys(maps.slugToId).filter(s => s.startsWith(q));
  return hits.length === 1 ? maps.slugToId[hits[0]] : null;
}
