// Datasworn -> dicebox oracle module.
//
// Reads one or more compiled Datasworn books (classic.json / delve.json /
// starforged.json, CC BY 4.0, Shawn Tomkin) and emits a compact ES module
// dicebox can lazy-load the way it loads the deck art. Each book's oracle tree
// is a shallow nest of collections -> tables -> rows; we keep the browse tree
// separate from a flat table index so rolling and cross-table links resolve by
// id. Multiple books merge into one set — Ironsworn folds in its Delve expansion.
//
//   node tools/build-oracles.mjs <out.js> <EXPORT_NAME> <book.json> [book2.json …]
//
// Row shape is terse: { a: min, b: max, t: text, r?: [link…] } where each link
// is { o: targetId|null, n: rolls, auto: 0|1 }. o null re-rolls this same table
// (the Datasworn "Roll twice" convention); a string rolls that table's id.
// auto:1 links resolve as part of the result; auto:0 are optional follow-ups.
import { readFileSync, writeFileSync } from 'node:fs';

const [, , outPath, exportName, ...bookPaths] = process.argv;
if (!outPath || !exportName || !bookPaths.length) {
  console.error('usage: build-oracles.mjs <out.js> <EXPORT_NAME> <book.json> [book2.json …]');
  process.exit(1);
}

const tables = {};        // id -> { name, sides, rows }
const tree = [];          // merged browse tree (each book's collections appended)
let tableCount = 0, rowCount = 0, linkCount = 0;

function diceToken(dice) {
  // Datasworn writes "1d100" / "1d10"; dicebox rolls a single dN, so keep sides.
  const m = /^\s*1d(\d+)\s*$/i.exec(dice || '');
  return m ? Number(m[1]) : 100;
}

function convertTable(id, tbl) {
  const rows = [];
  for (const row of tbl.rows || []) {
    if (row.min == null || row.max == null) continue; // skip non-rollable spacers
    const out = { a: row.min, b: row.max, t: (row.text || '').trim() };
    const links = (row.oracle_rolls || []).map(o => {
      const link = { o: o.oracle ?? null, n: o.number_of_rolls || 1, auto: o.auto ? 1 : 0 };
      if (o.duplicates && o.duplicates !== 'reroll') link.dup = o.duplicates;
      return link;
    });
    if (links.length) { out.r = links; linkCount += links.length; }
    rows.push(out);
    rowCount++;
  }
  tables[id] = { name: tbl.name, sides: diceToken(tbl.dice), rows };
  tableCount++;
  return id;
}

// Walk collections into a browse tree of { name, tables:[id…], groups:[…] }.
function convertCollection(coll) {
  const node = { name: coll.name };
  const tableIds = [];
  for (const [, tbl] of Object.entries(coll.contents || {})) {
    tableIds.push(convertTable(tbl._id, tbl));
  }
  if (tableIds.length) node.tables = tableIds;
  const groups = [];
  for (const [, sub] of Object.entries(coll.collections || {})) {
    groups.push(convertCollection(sub));
  }
  if (groups.length) node.groups = groups;
  return node;
}

let meta = null, first = true;
for (const path of bookPaths) {
  const book = JSON.parse(readFileSync(path, 'utf8'));
  if (!meta) meta = { id: book._id, title: book.title || book._id, authors: (book.authors || []).map(a => a.name), date: book.date, url: book.url, license: book.license };
  const colls = Object.values(book.oracles || {}).map(convertCollection);
  if (first) { tree.push(...colls); first = false; }
  else {
    // A supplement (Delve) nests under its own header so its collections do not
    // collide with the base book's ("Character", "Moves", …).
    const label = (book.title || '').split(': ').pop().replace(/ Rulebook$/, '');
    tree.push({ name: label, groups: colls });
  }
}

const data = { ...meta, tree, tables };

const banner = `// GENERATED by tools/build-oracles.mjs from Datasworn (${bookPaths.map(p => p.replace(/^.*\//, '').replace(/\.json$/, '')).join(' + ')}).\n`
  + `// Oracle text: ${meta.title} © ${meta.authors.join(', ')}, used under CC BY 4.0.\n`
  + `// Do not edit by hand — re-run the build.\n`;
writeFileSync(outPath, `${banner}export const ${exportName} = ${JSON.stringify(data)};\n`);

const bytes = Buffer.byteLength(readFileSync(outPath));
console.log(`${exportName}: ${tableCount} tables, ${rowCount} rows, ${linkCount} links -> ${outPath} (${bytes.toLocaleString()} bytes)`);
