// Datasworn -> dicebox oracle module.
//
// Reads a compiled Datasworn book (classic.json / delve.json / starforged.json,
// CC BY 4.0, Shawn Tomkin) and emits a compact ES module dicebox can lazy-load
// the way it loads the deck art. The book's oracle tree is a shallow nest of
// collections -> tables -> rows; we keep the browse tree separate from a flat
// table index so rolling and cross-table links resolve by id.
//
//   node tools/build-oracles.mjs <book.json> <out.js> <EXPORT_NAME>
//
// Row shape is terse: { a: min, b: max, t: text, r?: [link…] } where each link
// is { o: targetId|null, n: rolls, auto: 0|1 }. o null re-rolls this same table
// (the Datasworn "Roll twice" convention); a string rolls that table's id.
// auto:1 links resolve as part of the result; auto:0 are optional follow-ups.
import { readFileSync, writeFileSync } from 'node:fs';

const [, , inPath, outPath, exportName] = process.argv;
if (!inPath || !outPath || !exportName) {
  console.error('usage: build-oracles.mjs <book.json> <out.js> <EXPORT_NAME>');
  process.exit(1);
}

const book = JSON.parse(readFileSync(inPath, 'utf8'));
const tables = {};        // id -> { name, dice, rows }
let tableCount = 0, rowCount = 0, linkCount = 0;

function diceToken(dice) {
  // Datasworn writes "1d100" / "1d10"; dicebox rolls a single dN, so keep sides.
  const m = /^\s*1d(\d+)\s*$/i.exec(dice || '');
  return m ? Number(m[1]) : 100;
}

function convertTable(id, tbl) {
  const rows = [];
  for (const row of tbl.rows || []) {
    if (row.min == null || row.max == null) continue; // skip non-rollable spacers
    const out = { a: row.min, b: row.max, t: (row.text || '').trim() };
    const links = (row.oracle_rolls || []).map(o => {
      const link = { o: o.oracle ?? null, n: o.number_of_rolls || 1, auto: o.auto ? 1 : 0 };
      if (o.duplicates && o.duplicates !== 'reroll') link.dup = o.duplicates;
      return link;
    });
    if (links.length) { out.r = links; linkCount += links.length; }
    rows.push(out);
    rowCount++;
  }
  tables[id] = { name: tbl.name, sides: diceToken(tbl.dice), rows };
  tableCount++;
  return id;
}

// Walk collections into a browse tree of { name, tables:[id…], groups:[…] }.
function convertCollection(coll) {
  const node = { name: coll.name };
  const tableIds = [];
  for (const [, tbl] of Object.entries(coll.contents || {})) {
    tableIds.push(convertTable(tbl._id, tbl));
  }
  if (tableIds.length) node.tables = tableIds;
  const groups = [];
  for (const [, sub] of Object.entries(coll.collections || {})) {
    groups.push(convertCollection(sub));
  }
  if (groups.length) node.groups = groups;
  return node;
}

const tree = [];
for (const [, coll] of Object.entries(book.oracles || {})) {
  tree.push(convertCollection(coll));
}

const data = {
  id: book._id,
  title: book.title || book._id,
  authors: (book.authors || []).map(a => a.name),
  date: book.date,
  url: book.url,
  license: book.license,
  tree,
  tables,
};

const banner = `// GENERATED by tools/build-oracles.mjs from Datasworn (${book._id}).\n`
  + `// Oracle text: ${book.title} © ${(book.authors || []).map(a => a.name).join(', ')}, used under CC BY 4.0.\n`
  + `// Do not edit by hand — re-run the build.\n`;
writeFileSync(outPath, `${banner}export const ${exportName} = ${JSON.stringify(data)};\n`);

const bytes = Buffer.byteLength(readFileSync(outPath));
console.log(`${book._id}: ${tableCount} tables, ${rowCount} rows, ${linkCount} links -> ${outPath} (${bytes.toLocaleString()} bytes)`);
